import "../../modules/es.array.iterator";
import "../../modules/es.math.acosh";
import "../../modules/es.math.asinh";
import "../../modules/es.math.atanh";
import "../../modules/es.math.cbrt";
import "../../modules/es.math.clz32";
import "../../modules/es.math.cosh";
import "../../modules/es.math.expm1";
import "../../modules/es.math.fround";
import "../../modules/es.math.f16round";
import "../../modules/es.math.hypot";
import "../../modules/es.math.imul";
import "../../modules/es.math.log10";
import "../../modules/es.math.log1p";
import "../../modules/es.math.log2";
import "../../modules/es.math.sign";
import "../../modules/es.math.sinh";
import "../../modules/es.math.sum-precise";
import "../../modules/es.math.tanh";
import "../../modules/es.math.to-string-tag";
import "../../modules/es.math.trunc";
import path from "../../internals/path";
const _cjs_default = path.Math;
export default _cjs_default;
