import "../modules/web.atob";
import "../modules/web.btoa";
import "../modules/web.dom-collections.for-each";
import "../modules/web.dom-collections.iterator";
import "../modules/web.dom-exception.constructor";
import "../modules/web.dom-exception.stack";
import "../modules/web.dom-exception.to-string-tag";
import "../modules/web.immediate";
import "../modules/web.queue-microtask";
import "../modules/web.self";
import "../modules/web.structured-clone";
import "../modules/web.timers";
import "../modules/web.url";
import "../modules/web.url.can-parse";
import "../modules/web.url.parse";
import "../modules/web.url.to-json";
import "../modules/web.url-search-params";
import "../modules/web.url-search-params.delete";
import "../modules/web.url-search-params.has";
import "../modules/web.url-search-params.size";
import path from "../internals/path";
const _cjs_default = path;
export default _cjs_default;
