import "../../../modules/es.object.to-string";
import "../../../modules/es.regexp.exec";
import "../../../modules/es.string.at-alternative";
import "../../../modules/es.string.code-point-at";
import "../../../modules/es.string.ends-with";
import "../../../modules/es.string.includes";
import "../../../modules/es.string.match";
import "../../../modules/es.string.match-all";
import "../../../modules/es.string.pad-end";
import "../../../modules/es.string.pad-start";
import "../../../modules/es.string.repeat";
import "../../../modules/es.string.replace";
import "../../../modules/es.string.replace-all";
import "../../../modules/es.string.search";
import "../../../modules/es.string.split";
import "../../../modules/es.string.starts-with";
import "../../../modules/es.string.substr";
import "../../../modules/es.string.trim";
import "../../../modules/es.string.trim-start";
import "../../../modules/es.string.trim-end";
import "../../../modules/es.string.iterator";
import "../../../modules/es.string.anchor";
import "../../../modules/es.string.big";
import "../../../modules/es.string.blink";
import "../../../modules/es.string.bold";
import "../../../modules/es.string.fixed";
import "../../../modules/es.string.fontcolor";
import "../../../modules/es.string.fontsize";
import "../../../modules/es.string.italics";
import "../../../modules/es.string.link";
import "../../../modules/es.string.small";
import "../../../modules/es.string.strike";
import "../../../modules/es.string.sub";
import "../../../modules/es.string.sup";
import entryVirtual from "../../../internals/entry-virtual";
const _cjs_default = entryVirtual('String');
export default _cjs_default;
