import utils_1 from "./utils";
// Emums
const _ERROR = {
  OK: 0,
  INTERNAL: 1,
  STRICT: 2,
  CR_EXPECTED: 25,
  LF_EXPECTED: 3,
  UNEXPECTED_CONTENT_LENGTH: 4,
  UNEXPECTED_SPACE: 30,
  CLOSED_CONNECTION: 5,
  INVALID_METHOD: 6,
  INVALID_URL: 7,
  INVALID_CONSTANT: 8,
  INVALID_VERSION: 9,
  INVALID_HEADER_TOKEN: 10,
  INVALID_CONTENT_LENGTH: 11,
  INVALID_CHUNK_SIZE: 12,
  INVALID_STATUS: 13,
  INVALID_EOF_STATE: 14,
  INVALID_TRANSFER_ENCODING: 15,
  CB_MESSAGE_BEGIN: 16,
  CB_HEADERS_COMPLETE: 17,
  CB_MESSAGE_COMPLETE: 18,
  CB_CHUNK_HEADER: 19,
  CB_CHUNK_COMPLETE: 20,
  PAUSED: 21,
  PAUSED_UPGRADE: 22,
  PAUSED_H2_UPGRADE: 23,
  USER: 24,
  CB_URL_COMPLETE: 26,
  CB_STATUS_COMPLETE: 27,
  CB_METHOD_COMPLETE: 32,
  CB_VERSION_COMPLETE: 33,
  CB_HEADER_FIELD_COMPLETE: 28,
  CB_HEADER_VALUE_COMPLETE: 29,
  CB_CHUNK_EXTENSION_NAME_COMPLETE: 34,
  CB_CHUNK_EXTENSION_VALUE_COMPLETE: 35,
  CB_RESET: 31,
  CB_PROTOCOL_COMPLETE: 38
};
export { _ERROR as ERROR };
const _TYPE = {
  BOTH: 0,
  // default
  REQUEST: 1,
  RESPONSE: 2
};
export { _TYPE as TYPE };
const _FLAGS = {
  CONNECTION_KEEP_ALIVE: 1 << 0,
  CONNECTION_CLOSE: 1 << 1,
  CONNECTION_UPGRADE: 1 << 2,
  CHUNKED: 1 << 3,
  UPGRADE: 1 << 4,
  CONTENT_LENGTH: 1 << 5,
  SKIPBODY: 1 << 6,
  TRAILING: 1 << 7,
  // 1 << 8 is unused
  TRANSFER_ENCODING: 1 << 9
};
export { _FLAGS as FLAGS };
const _LENIENT_FLAGS = {
  HEADERS: 1 << 0,
  CHUNKED_LENGTH: 1 << 1,
  KEEP_ALIVE: 1 << 2,
  TRANSFER_ENCODING: 1 << 3,
  VERSION: 1 << 4,
  DATA_AFTER_CLOSE: 1 << 5,
  OPTIONAL_LF_AFTER_CR: 1 << 6,
  OPTIONAL_CRLF_AFTER_CHUNK: 1 << 7,
  OPTIONAL_CR_BEFORE_LF: 1 << 8,
  SPACES_AFTER_CHUNK_SIZE: 1 << 9
};
export { _LENIENT_FLAGS as LENIENT_FLAGS };
const _METHODS = {
  'DELETE': 0,
  'GET': 1,
  'HEAD': 2,
  'POST': 3,
  'PUT': 4,
  /* pathological */
  'CONNECT': 5,
  'OPTIONS': 6,
  'TRACE': 7,
  /* WebDAV */
  'COPY': 8,
  'LOCK': 9,
  'MKCOL': 10,
  'MOVE': 11,
  'PROPFIND': 12,
  'PROPPATCH': 13,
  'SEARCH': 14,
  'UNLOCK': 15,
  'BIND': 16,
  'REBIND': 17,
  'UNBIND': 18,
  'ACL': 19,
  /* subversion */
  'REPORT': 20,
  'MKACTIVITY': 21,
  'CHECKOUT': 22,
  'MERGE': 23,
  /* upnp */
  'M-SEARCH': 24,
  'NOTIFY': 25,
  'SUBSCRIBE': 26,
  'UNSUBSCRIBE': 27,
  /* RFC-5789 */
  'PATCH': 28,
  'PURGE': 29,
  /* CalDAV */
  'MKCALENDAR': 30,
  /* RFC-2068, section 19.6.1.2 */
  'LINK': 31,
  'UNLINK': 32,
  /* icecast */
  'SOURCE': 33,
  /* RFC-7540, section 11.6 */
  'PRI': 34,
  /* RFC-2326 RTSP */
  'DESCRIBE': 35,
  'ANNOUNCE': 36,
  'SETUP': 37,
  'PLAY': 38,
  'PAUSE': 39,
  'TEARDOWN': 40,
  'GET_PARAMETER': 41,
  'SET_PARAMETER': 42,
  'REDIRECT': 43,
  'RECORD': 44,
  /* RAOP */
  'FLUSH': 45,
  /* DRAFT https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html */
  'QUERY': 46
};
export { _METHODS as METHODS };
const _STATUSES = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,
  RESPONSE_IS_STALE: 110,
  // Unofficial
  REVALIDATION_FAILED: 111,
  // Unofficial
  DISCONNECTED_OPERATION: 112,
  // Unofficial
  HEURISTIC_EXPIRATION: 113,
  // Unofficial
  MISCELLANEOUS_WARNING: 199,
  // Unofficial
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  TRANSFORMATION_APPLIED: 214,
  // Unofficial
  IM_USED: 226,
  MISCELLANEOUS_PERSISTENT_WARNING: 299,
  // Unofficial
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  SWITCH_PROXY: 306,
  // No longer used
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  PAGE_EXPIRED: 419,
  // Unofficial
  ENHANCE_YOUR_CALM: 420,
  // Unofficial
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE_UNOFFICIAL: 430,
  // Unofficial
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  LOGIN_TIMEOUT: 440,
  // Unofficial
  NO_RESPONSE: 444,
  // Unofficial
  RETRY_WITH: 449,
  // Unofficial
  BLOCKED_BY_PARENTAL_CONTROL: 450,
  // Unofficial
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  CLIENT_CLOSED_LOAD_BALANCED_REQUEST: 460,
  // Unofficial
  INVALID_X_FORWARDED_FOR: 463,
  // Unofficial
  REQUEST_HEADER_TOO_LARGE: 494,
  // Unofficial
  SSL_CERTIFICATE_ERROR: 495,
  // Unofficial
  SSL_CERTIFICATE_REQUIRED: 496,
  // Unofficial
  HTTP_REQUEST_SENT_TO_HTTPS_PORT: 497,
  // Unofficial
  INVALID_TOKEN: 498,
  // Unofficial
  CLIENT_CLOSED_REQUEST: 499,
  // Unofficial
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  BANDWIDTH_LIMIT_EXCEEDED: 509,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  WEB_SERVER_UNKNOWN_ERROR: 520,
  // Unofficial
  WEB_SERVER_IS_DOWN: 521,
  // Unofficial
  CONNECTION_TIMEOUT: 522,
  // Unofficial
  ORIGIN_IS_UNREACHABLE: 523,
  // Unofficial
  TIMEOUT_OCCURED: 524,
  // Unofficial
  SSL_HANDSHAKE_FAILED: 525,
  // Unofficial
  INVALID_SSL_CERTIFICATE: 526,
  // Unofficial
  RAILGUN_ERROR: 527,
  // Unofficial
  SITE_IS_OVERLOADED: 529,
  // Unofficial
  SITE_IS_FROZEN: 530,
  // Unofficial
  IDENTITY_PROVIDER_AUTHENTICATION_ERROR: 561,
  // Unofficial
  NETWORK_READ_TIMEOUT: 598,
  // Unofficial
  NETWORK_CONNECT_TIMEOUT: 599 // Unofficial
};
export { _STATUSES as STATUSES };
const _FINISH = {
  SAFE: 0,
  SAFE_WITH_CB: 1,
  UNSAFE: 2
};
export { _FINISH as FINISH };
const _HEADER_STATE = {
  GENERAL: 0,
  CONNECTION: 1,
  CONTENT_LENGTH: 2,
  TRANSFER_ENCODING: 3,
  UPGRADE: 4,
  CONNECTION_KEEP_ALIVE: 5,
  CONNECTION_CLOSE: 6,
  CONNECTION_UPGRADE: 7,
  TRANSFER_ENCODING_CHUNKED: 8
};
export { _HEADER_STATE as HEADER_STATE }; // C headers
const _METHODS_HTTP = [_METHODS.DELETE, _METHODS.GET, _METHODS.HEAD, _METHODS.POST, _METHODS.PUT, _METHODS.CONNECT, _METHODS.OPTIONS, _METHODS.TRACE, _METHODS.COPY, _METHODS.LOCK, _METHODS.MKCOL, _METHODS.MOVE, _METHODS.PROPFIND, _METHODS.PROPPATCH, _METHODS.SEARCH, _METHODS.UNLOCK, _METHODS.BIND, _METHODS.REBIND, _METHODS.UNBIND, _METHODS.ACL, _METHODS.REPORT, _METHODS.MKACTIVITY, _METHODS.CHECKOUT, _METHODS.MERGE, _METHODS['M-SEARCH'], _METHODS.NOTIFY, _METHODS.SUBSCRIBE, _METHODS.UNSUBSCRIBE, _METHODS.PATCH, _METHODS.PURGE, _METHODS.MKCALENDAR, _METHODS.LINK, _METHODS.UNLINK, _METHODS.PRI,
// TODO(indutny): should we allow it with HTTP?
_METHODS.SOURCE, _METHODS.QUERY];
export { _METHODS_HTTP as METHODS_HTTP };
const _METHODS_ICE = [_METHODS.SOURCE];
export { _METHODS_ICE as METHODS_ICE };
const _METHODS_RTSP = [_METHODS.OPTIONS, _METHODS.DESCRIBE, _METHODS.ANNOUNCE, _METHODS.SETUP, _METHODS.PLAY, _METHODS.PAUSE, _METHODS.TEARDOWN, _METHODS.GET_PARAMETER, _METHODS.SET_PARAMETER, _METHODS.REDIRECT, _METHODS.RECORD, _METHODS.FLUSH,
// For AirPlay
_METHODS.GET, _METHODS.POST];
export { _METHODS_RTSP as METHODS_RTSP };
const _METHOD_MAP = (0, utils_1.enumToMap)(_METHODS);
export { _METHOD_MAP as METHOD_MAP };
const _H_METHOD_MAP = Object.fromEntries(Object.entries(_METHODS).filter(([k]) => k.startsWith('H')));
export { _H_METHOD_MAP as H_METHOD_MAP };
const _STATUSES_HTTP = [_STATUSES.CONTINUE, _STATUSES.SWITCHING_PROTOCOLS, _STATUSES.PROCESSING, _STATUSES.EARLY_HINTS, _STATUSES.RESPONSE_IS_STALE, _STATUSES.REVALIDATION_FAILED, _STATUSES.DISCONNECTED_OPERATION, _STATUSES.HEURISTIC_EXPIRATION, _STATUSES.MISCELLANEOUS_WARNING, _STATUSES.OK, _STATUSES.CREATED, _STATUSES.ACCEPTED, _STATUSES.NON_AUTHORITATIVE_INFORMATION, _STATUSES.NO_CONTENT, _STATUSES.RESET_CONTENT, _STATUSES.PARTIAL_CONTENT, _STATUSES.MULTI_STATUS, _STATUSES.ALREADY_REPORTED, _STATUSES.TRANSFORMATION_APPLIED, _STATUSES.IM_USED, _STATUSES.MISCELLANEOUS_PERSISTENT_WARNING, _STATUSES.MULTIPLE_CHOICES, _STATUSES.MOVED_PERMANENTLY, _STATUSES.FOUND, _STATUSES.SEE_OTHER, _STATUSES.NOT_MODIFIED, _STATUSES.USE_PROXY, _STATUSES.SWITCH_PROXY, _STATUSES.TEMPORARY_REDIRECT, _STATUSES.PERMANENT_REDIRECT, _STATUSES.BAD_REQUEST, _STATUSES.UNAUTHORIZED, _STATUSES.PAYMENT_REQUIRED, _STATUSES.FORBIDDEN, _STATUSES.NOT_FOUND, _STATUSES.METHOD_NOT_ALLOWED, _STATUSES.NOT_ACCEPTABLE, _STATUSES.PROXY_AUTHENTICATION_REQUIRED, _STATUSES.REQUEST_TIMEOUT, _STATUSES.CONFLICT, _STATUSES.GONE, _STATUSES.LENGTH_REQUIRED, _STATUSES.PRECONDITION_FAILED, _STATUSES.PAYLOAD_TOO_LARGE, _STATUSES.URI_TOO_LONG, _STATUSES.UNSUPPORTED_MEDIA_TYPE, _STATUSES.RANGE_NOT_SATISFIABLE, _STATUSES.EXPECTATION_FAILED, _STATUSES.IM_A_TEAPOT, _STATUSES.PAGE_EXPIRED, _STATUSES.ENHANCE_YOUR_CALM, _STATUSES.MISDIRECTED_REQUEST, _STATUSES.UNPROCESSABLE_ENTITY, _STATUSES.LOCKED, _STATUSES.FAILED_DEPENDENCY, _STATUSES.TOO_EARLY, _STATUSES.UPGRADE_REQUIRED, _STATUSES.PRECONDITION_REQUIRED, _STATUSES.TOO_MANY_REQUESTS, _STATUSES.REQUEST_HEADER_FIELDS_TOO_LARGE_UNOFFICIAL, _STATUSES.REQUEST_HEADER_FIELDS_TOO_LARGE, _STATUSES.LOGIN_TIMEOUT, _STATUSES.NO_RESPONSE, _STATUSES.RETRY_WITH, _STATUSES.BLOCKED_BY_PARENTAL_CONTROL, _STATUSES.UNAVAILABLE_FOR_LEGAL_REASONS, _STATUSES.CLIENT_CLOSED_LOAD_BALANCED_REQUEST, _STATUSES.INVALID_X_FORWARDED_FOR, _STATUSES.REQUEST_HEADER_TOO_LARGE, _STATUSES.SSL_CERTIFICATE_ERROR, _STATUSES.SSL_CERTIFICATE_REQUIRED, _STATUSES.HTTP_REQUEST_SENT_TO_HTTPS_PORT, _STATUSES.INVALID_TOKEN, _STATUSES.CLIENT_CLOSED_REQUEST, _STATUSES.INTERNAL_SERVER_ERROR, _STATUSES.NOT_IMPLEMENTED, _STATUSES.BAD_GATEWAY, _STATUSES.SERVICE_UNAVAILABLE, _STATUSES.GATEWAY_TIMEOUT, _STATUSES.HTTP_VERSION_NOT_SUPPORTED, _STATUSES.VARIANT_ALSO_NEGOTIATES, _STATUSES.INSUFFICIENT_STORAGE, _STATUSES.LOOP_DETECTED, _STATUSES.BANDWIDTH_LIMIT_EXCEEDED, _STATUSES.NOT_EXTENDED, _STATUSES.NETWORK_AUTHENTICATION_REQUIRED, _STATUSES.WEB_SERVER_UNKNOWN_ERROR, _STATUSES.WEB_SERVER_IS_DOWN, _STATUSES.CONNECTION_TIMEOUT, _STATUSES.ORIGIN_IS_UNREACHABLE, _STATUSES.TIMEOUT_OCCURED, _STATUSES.SSL_HANDSHAKE_FAILED, _STATUSES.INVALID_SSL_CERTIFICATE, _STATUSES.RAILGUN_ERROR, _STATUSES.SITE_IS_OVERLOADED, _STATUSES.SITE_IS_FROZEN, _STATUSES.IDENTITY_PROVIDER_AUTHENTICATION_ERROR, _STATUSES.NETWORK_READ_TIMEOUT, _STATUSES.NETWORK_CONNECT_TIMEOUT];
export { _STATUSES_HTTP as STATUSES_HTTP };
const _ALPHA = [];
export { _ALPHA as ALPHA };
for (let i = 'A'.charCodeAt(0); i <= 'Z'.charCodeAt(0); i++) {
  // Upper case
  _ALPHA.push(String.fromCharCode(i));
  // Lower case
  _ALPHA.push(String.fromCharCode(i + 0x20));
}
const _NUM_MAP = {
  0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9
};
export { _NUM_MAP as NUM_MAP };
const _HEX_MAP = {
  0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  A: 0XA,
  B: 0XB,
  C: 0XC,
  D: 0XD,
  E: 0XE,
  F: 0XF,
  a: 0xa,
  b: 0xb,
  c: 0xc,
  d: 0xd,
  e: 0xe,
  f: 0xf
};
export { _HEX_MAP as HEX_MAP };
const _NUM = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
export { _NUM as NUM };
const _ALPHANUM = _ALPHA.concat(_NUM);
export { _ALPHANUM as ALPHANUM };
const _MARK = ['-', '_', '.', '!', '~', '*', '\'', '(', ')'];
export { _MARK as MARK };
const _USERINFO_CHARS = _ALPHANUM.concat(_MARK).concat(['%', ';', ':', '&', '=', '+', '$', ',']);
export { _USERINFO_CHARS as USERINFO_CHARS }; // TODO(indutny): use RFC
const _URL_CHAR = ['!', '"', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~'].concat(_ALPHANUM);
export { _URL_CHAR as URL_CHAR };
const _HEX = _NUM.concat(['a', 'b', 'c', 'd', 'e', 'f', 'A', 'B', 'C', 'D', 'E', 'F']);
export { _HEX as HEX };
/* Tokens as defined by rfc 2616. Also lowercases them.
 *        token       = 1*<any CHAR except CTLs or separators>
 *     separators     = "(" | ")" | "<" | ">" | "@"
 *                    | "," | ";" | ":" | "\" | <">
 *                    | "/" | "[" | "]" | "?" | "="
 *                    | "{" | "}" | SP | HT
 */
const _TOKEN = ['!', '#', '$', '%', '&', '\'', '*', '+', '-', '.', '^', '_', '`', '|', '~'].concat(_ALPHANUM);
export { _TOKEN as TOKEN };
/*
 * Verify that a char is a valid visible (printable) US-ASCII
 * character or %x80-FF
 */
const _HEADER_CHARS = ['\t'];
export { _HEADER_CHARS as HEADER_CHARS };
for (let i = 32; i <= 255; i++) {
  if (i !== 127) {
    _HEADER_CHARS.push(i);
  }
}
// ',' = \x44
const _CONNECTION_TOKEN_CHARS = _HEADER_CHARS.filter(c => c !== 44);
export { _CONNECTION_TOKEN_CHARS as CONNECTION_TOKEN_CHARS };
const _QUOTED_STRING = ['\t', ' '];
export { _QUOTED_STRING as QUOTED_STRING };
for (let i = 0x21; i <= 0xff; i++) {
  if (i !== 0x22 && i !== 0x5c) {
    // All characters in ASCII except \ and "
    _QUOTED_STRING.push(i);
  }
}
const _HTAB_SP_VCHAR_OBS_TEXT = ['\t', ' '];
export { _HTAB_SP_VCHAR_OBS_TEXT as HTAB_SP_VCHAR_OBS_TEXT }; // VCHAR: https://tools.ietf.org/html/rfc5234#appendix-B.1
for (let i = 0x21; i <= 0x7E; i++) {
  _HTAB_SP_VCHAR_OBS_TEXT.push(i);
}
// OBS_TEXT: https://datatracker.ietf.org/doc/html/rfc9110#name-collected-abnf
for (let i = 0x80; i <= 0xff; i++) {
  _HTAB_SP_VCHAR_OBS_TEXT.push(i);
}
const _MAJOR = exports.NUM_MAP;
export { _MAJOR as MAJOR };
const _MINOR = exports.MAJOR;
export { _MINOR as MINOR };
const _SPECIAL_HEADERS = {
  'connection': _HEADER_STATE.CONNECTION,
  'content-length': _HEADER_STATE.CONTENT_LENGTH,
  'proxy-connection': _HEADER_STATE.CONNECTION,
  'transfer-encoding': _HEADER_STATE.TRANSFER_ENCODING,
  'upgrade': _HEADER_STATE.UPGRADE
};
export { _SPECIAL_HEADERS as SPECIAL_HEADERS };
const _default = {
  ERROR: _ERROR,
  TYPE: _TYPE,
  FLAGS: _FLAGS,
  LENIENT_FLAGS: _LENIENT_FLAGS,
  METHODS: _METHODS,
  STATUSES: _STATUSES,
  FINISH: _FINISH,
  HEADER_STATE: _HEADER_STATE,
  ALPHA: _ALPHA,
  NUM_MAP: _NUM_MAP,
  HEX_MAP: _HEX_MAP,
  NUM: _NUM,
  ALPHANUM: _ALPHANUM,
  MARK: _MARK,
  USERINFO_CHARS: _USERINFO_CHARS,
  URL_CHAR: _URL_CHAR,
  HEX: _HEX,
  TOKEN: _TOKEN,
  HEADER_CHARS: _HEADER_CHARS,
  CONNECTION_TOKEN_CHARS: _CONNECTION_TOKEN_CHARS,
  QUOTED_STRING: _QUOTED_STRING,
  HTAB_SP_VCHAR_OBS_TEXT: _HTAB_SP_VCHAR_OBS_TEXT,
  MAJOR: _MAJOR,
  MINOR: _MINOR,
  SPECIAL_HEADERS: _SPECIAL_HEADERS,
  METHODS_HTTP: _METHODS_HTTP,
  METHODS_ICE: _METHODS_ICE,
  METHODS_RTSP: _METHODS_RTSP,
  METHOD_MAP: _METHOD_MAP,
  H_METHOD_MAP: _H_METHOD_MAP,
  STATUSES_HTTP: _STATUSES_HTTP
};
const _cjs_default = {
  ["SPECIAL_HEADERS"]: _SPECIAL_HEADERS,
  ["MINOR"]: _MINOR,
  ["MAJOR"]: _MAJOR,
  ["HTAB_SP_VCHAR_OBS_TEXT"]: _HTAB_SP_VCHAR_OBS_TEXT,
  ["QUOTED_STRING"]: _QUOTED_STRING,
  ["CONNECTION_TOKEN_CHARS"]: _CONNECTION_TOKEN_CHARS,
  ["HEADER_CHARS"]: _HEADER_CHARS,
  ["TOKEN"]: _TOKEN,
  ["HEX"]: _HEX,
  ["URL_CHAR"]: _URL_CHAR,
  ["USERINFO_CHARS"]: _USERINFO_CHARS,
  ["MARK"]: _MARK,
  ["ALPHANUM"]: _ALPHANUM,
  ["NUM"]: _NUM,
  ["HEX_MAP"]: _HEX_MAP,
  ["NUM_MAP"]: _NUM_MAP,
  ["ALPHA"]: _ALPHA,
  ["STATUSES_HTTP"]: _STATUSES_HTTP,
  ["H_METHOD_MAP"]: _H_METHOD_MAP,
  ["METHOD_MAP"]: _METHOD_MAP,
  ["METHODS_RTSP"]: _METHODS_RTSP,
  ["METHODS_ICE"]: _METHODS_ICE,
  ["METHODS_HTTP"]: _METHODS_HTTP,
  ["HEADER_STATE"]: _HEADER_STATE,
  ["FINISH"]: _FINISH,
  ["STATUSES"]: _STATUSES,
  ["METHODS"]: _METHODS,
  ["LENIENT_FLAGS"]: _LENIENT_FLAGS,
  ["FLAGS"]: _FLAGS,
  ["TYPE"]: _TYPE,
  ["ERROR"]: _ERROR,
  ["default"]: _default
};
export default _cjs_default;
