import "../../stable/async-iterator";
import "../../modules/es.array.iterator";
import "../../modules/es.string.iterator";
import "../../modules/esnext.async-iterator.constructor";
import "../../modules/esnext.async-iterator.async-dispose";
import "../../modules/esnext.async-iterator.drop";
import "../../modules/esnext.async-iterator.every";
import "../../modules/esnext.async-iterator.filter";
import "../../modules/esnext.async-iterator.find";
import "../../modules/esnext.async-iterator.flat-map";
import "../../modules/esnext.async-iterator.for-each";
import "../../modules/esnext.async-iterator.from";
import "../../modules/esnext.async-iterator.map";
import "../../modules/esnext.async-iterator.reduce";
import "../../modules/esnext.async-iterator.some";
import "../../modules/esnext.async-iterator.take";
import "../../modules/esnext.async-iterator.to-array";
import "../../modules/web.dom-collections.iterator";
import path from "../../internals/path";
const _cjs_default = path.AsyncIterator;
export default _cjs_default;
