import "../../modules/es.array.iterator";
import "../../modules/es.object.to-string";
import "../../modules/es.string.iterator";
import "../../modules/es.iterator.constructor";
import "../../modules/es.iterator.drop";
import "../../modules/es.iterator.every";
import "../../modules/es.iterator.filter";
import "../../modules/es.iterator.find";
import "../../modules/es.iterator.flat-map";
import "../../modules/es.iterator.for-each";
import "../../modules/es.iterator.from";
import "../../modules/es.iterator.map";
import "../../modules/es.iterator.reduce";
import "../../modules/es.iterator.some";
import "../../modules/es.iterator.take";
import "../../modules/es.iterator.to-array";
import path from "../../internals/path";
const _cjs_default = path.Iterator.from;
export default _cjs_default;
