import "../../modules/es.object.to-string";
import "../../modules/es.array.iterator";
import "../../modules/es.set";
import "../../modules/es.string.iterator";
import "../../modules/esnext.set.from";
import "../../modules/esnext.set.add-all";
import "../../modules/esnext.set.delete-all";
import "../../modules/esnext.set.difference.v2";
import "../../modules/esnext.set.every";
import "../../modules/esnext.set.filter";
import "../../modules/esnext.set.find";
import "../../modules/esnext.set.join";
import "../../modules/esnext.set.intersection.v2";
import "../../modules/esnext.set.is-disjoint-from.v2";
import "../../modules/esnext.set.is-subset-of.v2";
import "../../modules/esnext.set.is-superset-of.v2";
import "../../modules/esnext.set.map";
import "../../modules/esnext.set.reduce";
import "../../modules/esnext.set.some";
import "../../modules/esnext.set.symmetric-difference.v2";
import "../../modules/esnext.set.union.v2";
import "../../modules/web.dom-collections.iterator";
import path from "../../internals/path";
const _cjs_default = path.Set.from;
export default _cjs_default;
