import "../../modules/es.object.to-string";
import "../../modules/es.array.iterator";
import "../../modules/es.map";
import "../../modules/es.string.iterator";
import "../../modules/esnext.map.from";
import "../../modules/esnext.map.delete-all";
import "../../modules/esnext.map.emplace";
import "../../modules/esnext.map.every";
import "../../modules/esnext.map.filter";
import "../../modules/esnext.map.find";
import "../../modules/esnext.map.find-key";
import "../../modules/esnext.map.get-or-insert";
import "../../modules/esnext.map.get-or-insert-computed";
import "../../modules/esnext.map.includes";
import "../../modules/esnext.map.key-of";
import "../../modules/esnext.map.map-keys";
import "../../modules/esnext.map.map-values";
import "../../modules/esnext.map.merge";
import "../../modules/esnext.map.reduce";
import "../../modules/esnext.map.some";
import "../../modules/esnext.map.update";
import "../../modules/web.dom-collections.iterator";
import path from "../../internals/path";
const _cjs_default = path.Map.from;
export default _cjs_default;
