import "../modules/es.error.to-string";
import "../modules/es.array.iterator";
import "../modules/es.object.keys";
import "../modules/es.object.to-string";
import "../modules/es.map";
import "../modules/es.set";
import "../modules/web.dom-exception.constructor";
import "../modules/web.dom-exception.stack";
import "../modules/web.dom-exception.to-string-tag";
import "../modules/web.structured-clone";
import path from "../internals/path";
const _cjs_default = path.structuredClone;
export default _cjs_default;
