import "../../modules/es.symbol";
import "../../modules/es.object.assign";
import "../../modules/es.object.create";
import "../../modules/es.object.define-property";
import "../../modules/es.object.define-properties";
import "../../modules/es.object.entries";
import "../../modules/es.object.freeze";
import "../../modules/es.object.from-entries";
import "../../modules/es.object.get-own-property-descriptor";
import "../../modules/es.object.get-own-property-descriptors";
import "../../modules/es.object.get-own-property-names";
import "../../modules/es.object.get-prototype-of";
import "../../modules/es.object.group-by";
import "../../modules/es.object.has-own";
import "../../modules/es.object.is";
import "../../modules/es.object.is-extensible";
import "../../modules/es.object.is-frozen";
import "../../modules/es.object.is-sealed";
import "../../modules/es.object.keys";
import "../../modules/es.object.prevent-extensions";
import "../../modules/es.object.proto";
import "../../modules/es.object.seal";
import "../../modules/es.object.set-prototype-of";
import "../../modules/es.object.values";
import "../../modules/es.object.to-string";
import "../../modules/es.object.define-getter";
import "../../modules/es.object.define-setter";
import "../../modules/es.object.lookup-getter";
import "../../modules/es.object.lookup-setter";
import "../../modules/es.json.to-string-tag";
import "../../modules/es.math.to-string-tag";
import "../../modules/es.reflect.to-string-tag";
import path from "../../internals/path";
const _cjs_default = path.Object;
export default _cjs_default;
